INSERT INTO Message (id, content) VALUES (1, 'My first message out of the data file');
INSERT INTO Message (id, content) VALUES (2, 'My second message out of the data file');
INSERT INTO Message (id, content) VALUES (3, 'My third message out of the data file');
INSERT INTO Message (id, content) VALUES (4, 'My fourth message out of the data file');
INSERT INTO Person (id, age, email_Address, name) VALUES (1, 26, 'ireneliusr@gmail.com', 'Shurun');
INSERT INTO Person (id, age, email_Address, name) VALUES (2, 2, 'xiang@gmail.com', 'Xiang');
INSERT INTO Person (id, age, email_Address, name) VALUES (3, 2, 'pang@gmail.com', 'pang');
INSERT INTO Person (id, age, email_Address, name) VALUES (4, 1, 'clara@gmail.com', 'clara');
INSERT INTO Address(id, line_one, line_two, state, postal_code, country) values(5, '3rd fllor', 'WindmillCroft', 'Glasgow', 'G4', 'UK');
INSERT INTO Person(id, age, email_address, name) VALUES (5, 50, 'steve@gmail.com', 'Steve');